apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: The python app
  annotations:
    github.com/project-slug: marceloluiz1/python-app
spec:
  type: service
  owner: team-dev
  lifecycle: experimental
